# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"F\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"6\n\x11\x43onnectionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\"1\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\tSubscribe\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t2\xdb\x02\n\x0b\x43hatService\x12#\n\x05Login\x12\r.LoginRequest\x1a\t.Response\"\x00\x12-\n\nConnection\x12\x12.ConnectionRequest\x1a\t.Response\"\x00\x12\x33\n\x10UserDisconnected\x12\x12.ConnectionRequest\x1a\t.Response\"\x00\x12<\n\x0c\x44isconnected\x12\x12.ConnectionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12*\n\x0fSubscribe_group\x12\n.Subscribe\x1a\t.Response\"\x00\x12\x30\n\x10SendMessageGroup\x12\x0f.MessageRequest\x1a\t.Response\"\x00\x12\'\n\tDiscovery\x12\r.LoginRequest\x1a\t.Response\"\x00\x32<\n\nChatClient\x12.\n\x0eReceiveMessage\x12\x0f.MessageRequest\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=43
  _globals['_LOGINREQUEST']._serialized_end=75
  _globals['_RESPONSE']._serialized_start=77
  _globals['_RESPONSE']._serialized_end=147
  _globals['_CONNECTIONREQUEST']._serialized_start=149
  _globals['_CONNECTIONREQUEST']._serialized_end=203
  _globals['_MESSAGEREQUEST']._serialized_start=205
  _globals['_MESSAGEREQUEST']._serialized_end=254
  _globals['_SUBSCRIBE']._serialized_start=256
  _globals['_SUBSCRIBE']._serialized_end=284
  _globals['_CHATSERVICE']._serialized_start=287
  _globals['_CHATSERVICE']._serialized_end=634
  _globals['_CHATCLIENT']._serialized_start=636
  _globals['_CHATCLIENT']._serialized_end=696
# @@protoc_insertion_point(module_scope)
